version: "3.8"

services:
  dotnet.questions:
    build:
      context: RuOverflow.Questions/
      dockerfile: ./RuOverflow.Questions/Dockerfile
    ports:
      - "11001:80"
    environment:
      - RuOverFlow_Question_ConnectionString=Host=postgres;Database=ruflow;User Id=postgres;Password=postgres;Port=5432;
      - RedisUrl=redis:6379
    depends_on:
      - redis
      - postgres
  redis:
    container_name: "redis"
    image: "redis"
    hostname: redis
    ports:
      - "6378:6379"
  mssql:
    image: "mcr.microsoft.com/mssql/server"
    user: root
    ports:
      - "1400:1433"
    volumes:
      - mssql-server-linux-data:/var/opt/mssql/data
    environment:
      SA_PASSWORD: "Password123"
      ACCEPT_EULA: "Y"
  postgres:
    image: postgres:14
    env_file:
      - ./RuOverflow.Questions/RuOverflow.Questions/postgres.env
    volumes:
      - postgres:/var/opt/postgres/data
    ports:
      - "5433:5432"

volumes:
  mssql-server-linux-data:
  postgres:
